### ISSUE TITLE
[Question] Using Betterrest Class method to JSONify a structure field

### ISSUE THREAD

**Issue by Jones-S** [robinscholz/better-rest#19]
Hi there,
Sorry for bothering you again and again.
I have the case where I need to write a custom endpoint to include more information about related pages so I can't use your default rest endpoint for my page.

Certain things should be returned like they do in your code.
Specifically I have a structure field which should be returned as an Array of entries with all the fields as key.

Example: 
I have a structure field in my blueprint:

```yml
         paragraphs:
            label: Paragraphs
            type: structure
            columns:
              title:
                width: 2/8
              text:
                width: 5/8
              inverted:
                width: 1/8
            fields:
              title:
                type: text
              text:
                type: textarea
              inverted:
                type: toggle
```

And I want it in this JSON form:

```json
"paragraphs": [
        {
          "title": "My title",
          "text": "My text...",
          "inverted": "false"
        },
        {
          "title": "Another title",
          "text": "More text:",
          "inverted": "true"
        },
```

No I could do something like:

```php
$paragraphs = $home->paragraphs()->toStructure();
$json = [];

foreach ($structures as $paragraph) {
            $json[] = [
              'title' => $paragraph->title()->toString(),
              'text' => $paragraph->text()->toString(),
              'inverted' => $paragraph->inverted()->toString(),
            ];
          }

```

But I thought of using some of your static methods that should be able to do the same, right?

```php
@include_once __DIR__ . '/vendor/autoload.php';

use Robinscholz\Betterrest;

//... code for setting up a custom endpoint...

$rest = new Robinscholz\Betterrest([
  'srcset' => false,
  'kirbytags' => false,
  'smartypants' => true,
  'language' => 'de',
  'query' => [
    'select' => 'files',
  ],
]);


$content = $rest->contentFromRequest(
    new \Kirby\Http\Request([
        url' => 'pages/home' // page I want to get the content from
    ])
);

$modified = $rest->modifyContent($content);

// ... code for returning that value
```

Or even further:
```php
// init new rest class instance... 
$paragraphs = $home->paragraphs();
$modified = $rest->modifyContent($paragraphs);

```

Sorry I am not super used to php, but as far as I understand your code:
https://github.com/robinscholz/better-rest/blob/62cee29b107d3e69fb7c733aee577ec39ee5ba7d/classes/Betterrest.php#L119

You use things recursively if it is an array or not and then return the data...
If you could provide some lines of code how I could use your class methods in my own endpoint to get some nice JSON that would be awesome.

I know this is quite a bit to ask, but as I dont know anybody fluent in PHP I don't really know where else to ask...

Thank you very much in advance.

Cheers
